---
resource_types:
- name: ubuntu-xenial-image
  type: docker-image
  privileged: true
  source:
    repository: harbor.tanzu-gss-labs.vmware.com/lab-automation/ubuntu
    tag: xenial
    ca_certs: ((harbor_root_ca_cert.certificate))
    insecure_registries: ["harbor.tanzu-gss-labs.vmware.com"]
resources:
- name: config
  type: git
  source:
    uri: ((cfauth-testing))
    private_key: ((rios-plat-auto-pipes-deploy-key.private_key))
    branch: main
jobs:
- name: login
  serial: true
  plan: 
  - get: config
  - get: ubuntu-xenial-image
  - task: auth-login
    image: ubuntu-xenial-image
    file: pipeline_test/task/
    params:
      CF_USERNAME: ((cf-username))
      CF_PASSWORD: ((cf-password))
      CF_TARGET: ((cf-api))